// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "14fa49af-e658-4df6-a6b7-66824f4e5c1c";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password
//these are all referenced in a separate file on Arduino Cloud,but I won't upload that because I don't want to give everyone my ssid

void onKdadjChange();
void onKiadjChange();
void onKpadjChange();

float error;
float Kdadj;
float Kiadj;
float Kpadj;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(error, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(Kdadj, READWRITE, ON_CHANGE, onKdadjChange);
  ArduinoCloud.addProperty(Kiadj, READWRITE, ON_CHANGE, onKiadjChange);
  ArduinoCloud.addProperty(Kpadj, READWRITE, ON_CHANGE, onKpadjChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
